# For more info on HTTP files go to https://aka.ms/vs/httpfile
@HostAddress = http://localhost:5156

GET {{HostAddress}}/weatherforecast/1
Accept: application/json

###
POST {{HostAddress}}/weatherforecast/
Content-Type: application/json
Accept: application/json

{
  "ProductName": "Example Product",
  "ProductDescription": "This is an example description"
}