version: '3.4'

services:
  catalog-db:
    image: postgres
    restart: always
    environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=CatalogDb
    ports:
        - "5433:5432"
    volumes:
        - postgres_catalog:/var/lib/postgresql/data/