version: '3.4'

services:
  catalog-db:
    image: postgres
  basket-db:
    image: postgres
  distributedcache:
    image: redis
  discount-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
  ordering-db:
   image: mcr.microsoft.com/mssql/server:2022-latest
 
  messagebroker:
   image: rabbitmq:management

  catalog-api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog-Api/Dockerfile

  basket-api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket-Api/Dockerfile

  discount_grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount-gRPC/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile

  ordering-api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering_Api/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
  sqlserver_discount:
  sqlserver_ordering:





